CS01 Interpolation using ML
BytesClub/CS-01 pull request #8
Opened 2017-12-21 18:37 UTC by Sameem25

The following problem has been done using Normal Equation for faster calculation. Cost function so calculated finally is least.

2017-12-22 07:22 UTC, RudraNilBasu requested changes
* Make sure to send PRs from a new branch (other than master)
* Follow Bytes Club's commit message style
* Run the code through PyLint for coding guidelines

2017-12-22 07:22 UTC, RudraNilBasu commented on pset0/CS01_interpolation.py
> +year_arr=[]
Space before and after =

2017-12-22 07:22 UTC, RudraNilBasu commented on pset0/CS01_interpolation.py
> +profit_arr=[]
Here too

2017-12-22 18:02 UTC, Sameem25 commented
So will I create a new PR with from a new branch and correcting the errors?

2017-12-23 06:43 UTC, RudraNilBasu commented
@Sameem25 keep it for now, create a new branch for next PRs

2017-12-23 15:16 UTC, Progyan1997 commented
@Sameem25 Along with modifying the current errors, make your solution to the point and modular. And the file should be inside directory `Sameem25`.

2017-12-23 15:23 UTC, Sameem25 commented on pset0/CS01_interpolation.py
> +profit_arr=[]
Okay

2017-12-23 15:23 UTC, Sameem25 commented
Okay

2017-12-23 15:25 UTC, Sameem25 commented
Should I remove the graphs and make it short or reduce the number of code lines?

2017-12-23 15:27 UTC, Progyan1997 commented
@Sameem25 i think that's what I wanted! 👍

2017-12-30 09:58 UTC, closed without merging