CS01 Interpolation
BytesClub/CS-01 pull request #9
Opened 2017-12-24 14:14 UTC by Sameem25

The following program can predict future profits for the corresponding year upon the request of the user.

2017-12-24 18:36 UTC, RudraNilBasu requested changes
Thanks for the PR, can you squash the commits in a single commit following the format: https://bytesclub.github.io/contributing/#tips-for-contribution

2017-12-24 18:36 UTC, RudraNilBasu commented on pset0/sameem25/CS01.py
> +    profit= float(input("Enter the profit for the year: "))
A space before the = also (Same for lines 25 and 26)

2017-12-24 18:36 UTC, RudraNilBasu commented on pset0/sameem25/CS01.py
> +    b=np.insert(year, 0, 1, axis=1)
Space before and after =

2017-12-24 18:36 UTC, RudraNilBasu commented on pset0/sameem25/CS01.py
> +c=b[:,1]**2
Here too.

2017-12-25 09:49 UTC, Sameem25 commented
The changes have been made.

2017-12-28 17:40 UTC, RudraNilBasu reviewed
Regarding the commit messages, can you break them at 80 character limits as present in BytesClub.github.io/contributing ?

2017-12-28 18:57 UTC, Sameem25 commented
Well, now the commit message is according to Bytes Club's rule.

2017-12-29 13:24 UTC, RudraNilBasu approved these changes

2017-12-30 08:00 UTC, 0xTheProDev requested changes
Rename the file to be _**Interpolation.py**_ and remove additional print statements. Otherwise good to go!

2017-12-30 08:16 UTC, Sameem25 commented
Well, the file name is changed and the print statements as well. Note there is only one print statement at the end to show output and no additional 'print' statements.

2017-12-30 09:53 UTC, merged